### ISSUE TITLE
Actividad 04

### ISSUE THREAD

**Issue by Quesomora** [ech0server/ech0server.github.io#1]
Profe, cuando suba una actividad no nos haga buscarla en todos los archivos de su repo, porfa.

**Comment by ech0server** [comment]
Hay varias opciones:

- Crear una pagina nueva con puras actividades, pendiente investigar si se pueden hacer sub-paginas.
- Crear una categoria para actividades
- Crear un nuevo repositorio solo con las actividades

Sugerencias?

**Comment by Quesomora** [comment]
Creo que con la página (y/o sub-páginas) es más que suficiente, ya estoy usando un cliente RSS para ver tanto noticias como el feed de los post que sube (aunque eso incluye el curso de seguridad).
Para las otras opciones es más complejo recibir una notificación cuando suba una nueva actividad.
